### PR TITLE
Remove warning message from init function

### PR DESCRIPTION
**Pull request by giordano**
Per https://github.com/JuliaPackaging/HistoricalStdlibVersions.jl/pull/7#issuecomment-1326778678

### CODE REVIEW

**Review by IanButterworth — APPROVED** [review]

**Comment by IanButterworth** [comment]
I don't see why we need to have every check pass here

**Comment by DilumAluthge** [comment]
I've updated the branch protection settings.

**Comment by giordano** [comment]
But do we need to run that job at all in CI?

**Comment by DilumAluthge** [comment]
Is there a reason not to? It's an easy way to be notified that an update is available.

**Pull request merged**
